#lang racket

(require "planner.rkt")

(define medieval-domain 
  (domain (constants (character (knight princess))
                     (location (castle armory blacksmith river enchanted-forest)))
          (actions (move ([c character] [cur location] [to location])
                         (preconds (adj (cur to) = #t)
                                   (free (c) = #t)
                                   (loc (c) = cur)
                                   (loc (knight) = cur)
                                   (~ loc (dragon) = cur))
                         (effects (loc (c) <- to)))
                   (equip-sword ()
                                (preconds (loc (knight) = blacksmith))
                                (effects (sword () <- #t)))
                   (equip-shield ()
                                 (preconds (loc (knight) = armory))
                                 (effects (shield () <- #t)))
                   (sleigh-dragon ([c location])
                                  (preconds (loc (knight) = c)
                                            (loc (dragon) = c)
                                            (sword () = #t)
                                            (shield () = #t))
                                  (effects (loc (dragon) <- hell)))
                   (rescue-princess ([c location])
                                    (preconds (loc (knight) = c)
                                              (loc (princess) = c))
                                    (effects (free (princess) <- #t))))))

(define start (state (adj (<=> castle blacksmith))
                     (adj (<=> castle armory))
                     (adj (<=> castle river))
                     (adj (<=> river enchanted-forest))
                     (free (knight))
                     (loc (knight) = castle)
                     (loc (dragon) = river)
                     (loc (princess) = enchanted-forest)))                     

(define goal (state (loc (knight) = castle)
                    (loc (princess) = castle)))

(fwd-search medieval-domain start goal)

#| -> 
'((move knight castle armory)
  (equip-shield)
  (move knight armory castle)
  (move knight castle blacksmith)
  (equip-sword)
  (move knight blacksmith castle)
  (move knight castle river)
  (sleigh-dragon river)
  (move knight river enchanted-forest)
  (rescue-princess enchanted-forest)
  (move princess enchanted-forest river)
  (move knight enchanted-forest river)
  (move princess river castle)
  (move knight river castle))
|#